def job_repourl = "https://github.com"
def job_repouser = "ShadowUser17"
def job_repobranch = "master"
def job_repolist = ["ssh-parser"]

for(repo_item in job_repolist) {
    job(repo_item) {
        scm {
            git("${job_repourl}/${job_repouser}/${repo_item}", job_repobranch)
        }
        steps {
            shell("bash ./build.sh")
            shell("./cmd/${repo_item} -h")
        }
    }
}
